- name: make main file location across the nodes
  become: yes
  file: 
    path: "{{ crdb_file_location }}/{{ kafka_username }}"
    state: directory
    mode: '0777'
    owner: "{{ kafka_username }}"
    group: "{{ kafka_username }}"
