- name: fix  var log kafka permission for kafka connect
  become: yes
  shell:
    cmd: chmod 770 /var/log/kafka
  ignore_errors: yes

- name: Set to Realistic Hostname
  when: include_kafka == "yes"
  hostname:
    name: "kafka"

- name: Setup Hostsfile
  when: include_kafka == "yes"
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: "127.0.0.1 localhost kafka"
    state: present

- name: restart_nginx
  when: include_kafka == "yes"
  service:
    name: nginx
    state: restarted
