- name: make certs dir
  become: yes
  file:
    path: "/home/{{ login_username }}/certs"
    state: directory
    mode: '0755'
    owner: "{{ login_username }}"
    group: "{{ login_username }}"

- name: make my-safe-directory dir
  become: yes
  file:
    path: "/home/{{ login_username }}/my-safe-directory"
    state: directory
    mode: '0755'
    owner: "{{ login_username }}"
    group: "{{ login_username }}"

- name: create ca.crt
  copy:
    src: "./temp/{{region}}/tls_cert"
    dest: /home/"{{ login_username }}"/certs/ca.crt
    mode: '0400'

- name: create client.db_admin_user.crt
  copy:
    src: "./temp/{{region}}/tls_user_cert"
    dest: "/home/{{ login_username }}/certs/client.{{db_admin_user}}.crt"
    mode: '0400'

- name: create client.db_admin_user.key
  copy:
    src: "./temp/{{region}}/tls_user_key"
    dest: "/home/{{ login_username }}/certs/client.{{db_admin_user}}.key"
    mode: '0400'

- name: create ca.pub
  copy:
    src: "./temp/{{region}}/tls_public_key"
    dest: "/home/{{ login_username }}/certs/ca.pub"
    mode: '0400'

- name: create ca.key
  copy:
    src: "./temp/{{region}}/tls_private_key"
    dest: "/home/{{ login_username }}/my-safe-directory/ca.key"
    mode: '0400'

- name: copy keys for passwordless ssh between nodes
  copy:
    dest: "/home/{{ login_username }}/.ssh/id_rsa"
    src: "/home/{{ login_username }}/my-safe-directory/ca.key"
    remote_src: yes
    mode: '0400'

- name: add to authorized keys
  shell:
    cmd: "ssh-keygen -y -f /home/{{ login_username }}/.ssh/id_rsa >> /home/{{ login_username }}/.ssh/authorized_keys"
