- name: make main file location across the nodes
  become: yes
  file: 
    path: "{{ crdb_file_location }}/{{ login_username }}"
    state: directory
    mode: '0777'
    owner: "{{ login_username }}"
    group: "{{ login_username }}"
