- name: change grafana admin password
  become: yes
  shell:
    cmd: "grafana-cli admin reset-admin-password "{{ db_admin_password }}""

- name: create prometheus datasource
  community.grafana.grafana_datasource:
    name: prometheus
    ds_type: prometheus
    ds_url: https://openshift-monitoring.company.com
    access: proxy
    url: http://localhost:9090
    url_username: admin
    url_password: "{{ db_admin_password }}"
    enforce_secure_data: true

- name: Import Grafana dashboards for crdb
  community.grafana.grafana_dashboard:
    state: present
    commit_message: Updated by ansible
    overwrite: true
    path: https://github.com/cockroachdb/cockroach/blob/master/monitoring/grafana-dashboards/by-cluster/changefeeds.json
    url: http://localhost:9090
    url_username: admin
    url_password: "{{ db_admin_password }}"

- name: Import Grafana replicator dashboard 
  community.grafana.grafana_dashboard:
    state: present
    commit_message: Updated by ansible
    overwrite: true
    path: https://github.com/cockroachdb/replicator/blob/master/scripts/dashboard/replicator.json
    url: http://localhost:9090
    url_username: admin
    url_password: "{{ db_admin_password }}"

