---
- name: Alerting rules file
  ansible.builtin.template:
    src: "alert.rules.j2"
    dest: "{{ prometheus_config_dir }}/rules/ansible_managed.rules"
    owner: root
    group: "{{ prometheus_system_group }}"
    mode: 0640
    validate: "{{ _prometheus_binary_install_dir }}/promtool check rules %s"
  when:
    - prometheus_alert_rules != []
    - not prometheus_agent_mode
  notify:
    - reload prometheus

- name: Alerting cockroach rules file
  ansible.builtin.copy:
    src: "alerts.rules.yml"
    dest: "{{ prometheus_config_dir }}/rules/alerts.rules.yml"
    owner: root
    group: "{{ prometheus_system_group }}"
    mode: 0640
    validate: "{{ _prometheus_binary_install_dir }}/promtool check rules %s"
  when:
    - prometheus_alert_rules != []
    - not prometheus_agent_mode
  notify:
    - reload prometheus

- name: aggregation cockroach rules file
  ansible.builtin.copy:
    src: "aggregation.rules.yml"
    dest: "{{ prometheus_config_dir }}/rules/aggregation.rules.yml"
    owner: root
    group: "{{ prometheus_system_group }}"
    mode: 0640
    validate: "{{ _prometheus_binary_install_dir }}/promtool check rules %s"
  when:
    - prometheus_alert_rules != []
    - not prometheus_agent_mode
  notify:
    - reload prometheus

- name: Copy custom alerting rule files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/rules/"
    owner: root
    group: "{{ prometheus_system_group }}"
    mode: 0640
    validate: "{{ _prometheus_binary_install_dir }}/promtool check rules %s"
  with_fileglob: "{{ prometheus_alert_rules_files }}"
  when:
    - not prometheus_agent_mode
  notify:
    - reload prometheus

- name: copy ca.crt for prometheus.yml
  become: true
  ansible.builtin.copy:
    src: /home/adminuser/certs/ca.crt
    dest: "{{ prometheus_config_dir }}/ca.crt"
    remote_src: yes
    mode: 0640
    owner: root
    group: prometheus

- name: Configure prometheus
  ansible.builtin.template:
    src: "{{ prometheus_config_file }}"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: true
    owner: root
    group: "{{ prometheus_system_group }}"
    mode: 0640

# - name validate prometheus file
#   ansible.utils.validate: 
#     data: "{{ _prometheus_binary_install_dir }}/promtool check config {{ prometheus_config_dir }}/prometheus.yml"
#     criteria: "{{ false if (lookup('env', 'CI')) or (lookup('env', 'MOLECULE_PROVISIONER_NAME')) else true }}"
#   notify:
#     - reload prometheus

- name: Configure Prometheus web
  ansible.builtin.copy:
    content: "{{ prometheus_web_config | to_nice_yaml(indent=2, sort_keys=False) }}"
    dest: "{{ prometheus_config_dir }}/web.yml"
    force: true
    owner: root
    group: "{{ prometheus_system_group }}"
    mode: 0640

- name: Configure prometheus static targets
  ansible.builtin.copy:
    content: |
      {{ item.value | to_nice_yaml(indent=2, sort_keys=False) }}
    dest: "{{ prometheus_config_dir }}/file_sd/{{ item.key }}.yml"
    force: true
    owner: root
    group: "{{ prometheus_system_group }}"
    mode: 0640
  with_dict: "{{ prometheus_targets }}"
  when: prometheus_targets != {}

- name: Copy prometheus custom static targets
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/file_sd/"
    force: true
    owner: root
    group: "{{ prometheus_system_group }}"
    mode: 0640
  with_fileglob: "{{ prometheus_static_targets_files }}"
