---
# roles/app-prometheus/tasks/install-grafana.yml

- name: Debug OS information
  become: yes
  ansible.builtin.debug:
    msg: "Distribution={{ ansible_facts['distribution'] }}  pkg_mgr={{ ansible_facts['pkg_mgr'] }}"

# ----------------------------------------
# RHEL/CentOS (yum/dnf) path
# ----------------------------------------
- name: Import Grafana GPG key (RHEL/CentOS)
  become: yes
  shell: rpm --import https://rpm.grafana.com/gpg.key
  when: ansible_facts['pkg_mgr'] in ['yum','dnf']

- name: Add Grafana YUM repo
  become: yes
  ansible.builtin.template:
    src: grafana.repo.j2
    dest: /etc/yum.repos.d/grafana.repo
    mode: '0644'
  when: ansible_facts['pkg_mgr'] in ['yum','dnf']

- name: Install Grafana (RHEL/CentOS)
  become: yes
  ansible.builtin.dnf:
    name: grafana
    state: latest
  when: ansible_facts['pkg_mgr'] in ['yum','dnf']

# ----------------------------------------
# Debian/Ubuntu (apt) path
# ----------------------------------------
- name: Install prerequisites for apt (Debian/Ubuntu)
  become: yes
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
      - wget
    state: latest
    update_cache: yes
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: Add Grafana GPG key (Debian/Ubuntu)
  become: yes
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: Add Grafana APT repo (Debian/Ubuntu)
  become: yes
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    filename: grafana
    state: present
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: Update apt cache (Debian/Ubuntu)
  become: yes
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: Install Grafana (Debian/Ubuntu)
  become: yes
  ansible.builtin.apt:
    name: grafana
    state: latest
  when: ansible_facts['pkg_mgr'] == 'apt'

# ----------------------------------------
# Common tasks
# ----------------------------------------
- name: Create systemd service unit for Grafana
  become: yes
  ansible.builtin.template:
    src: grafana.service.j2
    dest: /etc/systemd/system/grafana-server.service
    mode: '0644'
  notify: restart grafana-server
