- name: stop firewalld
  become: yes
  ignore_errors: true
  shell:
    cmd: "systemctl stop firewalld"

- name: disable firewalld
  become: yes
  ignore_errors: true
  shell:
    cmd: "systemctl disable firewalld"
