# roles/haproxy-node/tasks/install-haproxy.yml
---
- name: Install haproxy package
  become: yes
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Ensure HAProxy runtime directory exists
  become: yes
  ansible.builtin.file:
    path: /run/haproxy
    state: directory
    mode: '0755'

- name: Set up haproxy.cfg file
  become: yes
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
