- name: save external and internal ip addresses
  include_tasks: save-ips.yml
  when:
    - save_ips|bool

- name: disable firewalld
  include_tasks: firewalld.yml
  when:
    - firewalld|bool

- name: install haproxy
  import_tasks: install-haproxy.yml
  when:
    - install_haproxy|bool

- name: start haproxy
  import_tasks: start-haproxy.yml
  when:
    - start_haproxy|bool
