- name: Change selinux setting to allow haproxy to connect to any port
  become: yes
  ansible.builtin.command: setsebool -P haproxy_connect_any=1
  when:
    - ansible_selinux is defined
    - ansible_selinux.status == "enabled"

- name: Ensure haproxy is enabled and running
  become: yes
  ansible.builtin.service:
    name: haproxy
    enabled: yes
    state: started

# handlers/main.yml
# -----------------
- name: Reload haproxy
  become: yes
  ansible.builtin.service:
    name: haproxy
    state: reloaded
