- name: change selinux setting to allow haproxy to connect to any port
  become: yes
  command: setsebool -P haproxy_connect_any=1
  when:
    - ansible_selinux is defined
    - ansible_selinux.status == "enabled"

- name: run haproxy
  become: yes
  shell:
    cmd: systemctl start haproxy

- name: enable haproxy
  become: yes
  shell:
    cmd: systemctl enable haproxy
