# roles/haproxy-node/tasks/start-haproxy.yml
---
- name: Change selinux setting to allow haproxy to connect to any port
  become: yes
  ansible.builtin.command: setsebool -P haproxy_connect_any=1
  when:
    - ansible_selinux is defined
    - ansible_selinux.status == "enabled"

- name: Reload systemd & restart haproxy
  become: yes
  block:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart and enable haproxy service
      ansible.builtin.service:
        name: haproxy
        state: restarted
        enabled: yes
