- hosts: all_public_node_ips
  gather_facts: True
  roles:
    - common
- hosts: haproxy_node_ips
  gather_facts: True
  roles:
    - haproxy-node
- hosts: crdb_node_ips
  gather_facts: True
  roles:
    - crdb-node
- hosts: crdb_node_ips_0
  gather_facts: True
  roles:
    - crdb-node-0
- hosts: app_node_ips
  gather_facts: True
  roles:
    - app-node
- hosts: app_node_ips
  gather_facts: True
  roles:
    - replicator-molt
- hosts: haproxy_node_ips
  gather_facts: True
  roles:
    - app-prometheus
- hosts: kafka_node_ips
  gather_facts: false
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - kafka-node
