- name: make log replicator directory
  become: yes
  file: 
    path: "{{ crdb_file_location }}/{{ login_username }}/logs/replicator"
    state: directory
    mode: '0777'
    owner: "{{login_username}}"
    group: "{{login_username}}"

- name: make app log directory
  become: yes
  file: 
    path: "{{ crdb_file_location }}/{{ login_username }}/logs/bank-app"
    state: directory
    mode: '0777'
    owner: "{{login_username}}"
    group: "{{login_username}}"

- name: Create a directory if it does not exist
  become: yes
  file:
    path: /opt
    state: directory
    mode: '0755'
    owner: "{{login_username}}"
    group: "{{login_username}}"
