# save tls keys from app node to local machine
- name: Changing perm of ca.crt
  file: 
    path: /home/adminuser/certs/ca.crt
    state: file
    mode: 0644

- name: Changing perm of client.db_admin_user.crt
  file: 
    path: /home/adminuser/certs/client.{{ db_admin_user }}.crt
    state: file
    mode: 0644

- name: Changing perm of client.db_admin_user.key
  file: 
    path: /home/adminuser/certs/client.{{ db_admin_user }}.key
    state: file
    mode: 0644

- name: save ca.crt  locally
  fetch:
    dest: "temp/{{ region }}/ca.crt"
    src: /home/adminuser/certs/ca.crt
    flat: yes

- name: save client.db_admin_user.crt locally
  fetch:
    dest: "temp/{{ region }}/client.{{ db_admin_user }}.crt"
    src: "/home/adminuser/certs/client.{{ db_admin_user }}.crt"
    flat: yes

- name: save client.db_admin_user.key locally
  fetch:
    dest: "temp/{{ region }}/client.{{ db_admin_user }}.key"
    src: "/home/adminuser/certs/client.{{ db_admin_user }}.key"
    flat: yes
