# Installing and Configuring multi-region Demo
- name: Install multi-region packages
  become: yes
  yum:
    state: latest
    name:
      - gcc
      - gcc-c++
      - libpq-devel

- name
  become: yes
  pip:
    name:
      - sqlalchemy~=1.4
      - sqlalchemy-cockroachdb
      - psycopg2

# ignore errors because get an error if running this second time after updating scripts/setEnv.sh
- name: checkout Digital Banking git repo
  ignore_errors: yes
  git:
    repo: 'https://github.com/nollenr/crdb-multi-region-demo.git'
    dest: /opt/crdb-multi-region-demo
