# install npm depencies for nextEcommerce
- name: Install npm dependencies (nextEcommerce)
  shell: npm install
  args:
    chdir: "/opt/nextEcommerce"
    executable: /bin/bash
  environment:
    HOME: "/home/{{ login_username }}"
- name: save environment script
  copy:
    content: "{{ lookup('template','setEenv.j2') }}"
    dest: /opt/nextEcommerce/.env
    mode: '0755'
