- name: Install python3 pip
  become: yes
  yum:
    name: python3-pip
    state: latest

- name: install dbworkload for postgres and cockroachdb
  shell:
    cmd: pip3 install dbworkload[postgres]

- name: Create a directory if it does not exist
  file:
    path: /opt/dbworkload
    state: directory
    mode: '0755'

- name: save sample dbworkload script
  copy:
    content: "{{ lookup('template','dbworkload.j2') }}"
    dest: /opt/dbworkload/dbworkload.sh
    owner: adminuser
    group: adminuser
    mode: '0755'

- name: wget workload class
  get_url:
    url: 'https://raw.githubusercontent.com/fabiog1901/dbworkload/main/workloads/postgres/bank.py'
    dest: /opt/dbworkload/bank.py

- name: wget workload DDL file
  get_url:
    url: 'https://raw.githubusercontent.com/fabiog1901/dbworkload/main/workloads/postgres/bank.sql'
    dest: /opt/dbworkload/bank.sql

- name: wget workload datageneration file
  get_url:
    url: 'https://raw.githubusercontent.com/fabiog1901/dbworkload/main/workloads/postgres/bank.yaml'
    dest: /opt/dbworkload/bank.yaml
