- name: Get_nvm_install_script | {{ role_name | basename }}
  tags: Get_nvm_install_script
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh
    dest: "/home/{{ login_username }}/nvm_install.sh"
    force: true

- name: Install_or_update_nvm | {{ role_name | basename }}
  tags: Install_or_update_nvm
  command: bash /home/{{ login_username }}/nvm_install.sh

- name: Install_nodejs | {{ role_name | basename }}
  tags: Install_nodejs
  shell: |
    source /home/{{ login_username }}/.nvm/nvm.sh
    nvm install {{ node_version }}
  args:
    executable: /bin/bash
