- name: Install npm dependencies (nextEcommerce)
  tags: Install_ecommerce
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm use {{ node_version }}
    cd /opt/nextEcommerce
    npm install
  args:
    executable: /bin/bash

- name: Save environment script for nextEcommerce
  tags: Install_ecommerce
  copy:
    dest: /opt/nextEcommerce/.env
    mode: '0644'
    content: "{{ lookup('template', 'setEenv.j2') }}"
