- name: Install python3 pip
  become: yes
  yum:
    name: 
      - python3
      - python3-pip
    state: latest

- name: Ensure virtualenv is installed
  pip:
    name: virtualenv
    executable: pip3
