- name: Install python3 on all distros
  become: yes
  package:
    name: python3
    state: latest

- name: Refresh apt cache (Debian/Ubuntu only)
  become: yes
  apt:
    update_cache: yes
  when: ansible_facts.pkg_mgr == 'apt'

- name: Install pip on Ubuntu
  become: yes
  apt:
    name: python3-pip
    state: latest
  when: ansible_facts.pkg_mgr == 'apt'

- name: Install pip on RHEL/CentOS
  become: yes
  yum:
    name: python3-pip
    state: latest
  when: ansible_facts.pkg_mgr in ['yum','dnf']

- name: Ensure virtualenv is installed
  become: yes
  pip:
    name: virtualenv
    executable: pip3
