- name: Install system packages on Debian/Ubuntu
  become: yes
  apt:
    name:
      - gcc
      - g++
      - libpq-dev
      - python3-dev
      - postgresql-server-dev-all
    state: latest
    update_cache: yes
  when: ansible_facts.pkg_mgr == 'apt'

- name: Install system packages on RHEL/CentOS
  become: yes
  yum:
    name:
      - gcc
      - gcc-c++
      - postgresql-devel
      - python3-devel
      - libpq-devel
    state: latest
  when: ansible_facts.pkg_mgr in ['yum','dnf']

- name: Install sqlalchemy and psycopg2
  become: yes
  pip:
    name:
      - sqlalchemy~=1.4
      - sqlalchemy-cockroachdb
      - psycopg2
    executable: pip3
