- name: save environment script
  copy:
    content: "{{ lookup('template','setEnv.j2') }}"
    dest: /opt/Digital-Banking-CockroachDB/scripts/setEnv.sh
    mode: '0755'

- name: compile application
  shell:
    cmd: mvn clean package
    chdir: /opt/Digital-Banking-CockroachDB
