- name: Get the IPs
  set_fact:
    ip_ext_node: "{{ inventory_hostname }}"
    ip_int_node: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: save external ip to app node
  copy:
    content: "{{ ip_ext_node }}"
    dest: app_external_ip.txt

- name: Create local directory by region
  ansible.builtin.file:
    path: "temp/{{ region }}/"
    state: directory
  register: local_dir
  delegate_to: localhost

- name: save external ip locally
  fetch:
    dest: "temp/{{ region }}/app_external_ip{{ ip_ext_node }}.txt"
    src: app_external_ip.txt
    flat: yes

- name: save external ip locally without ip in name
  fetch:
    dest: "temp/{{ region }}/app_external_ip.txt"
    src: app_external_ip.txt
    flat: yes

- name: save internal ip to app node
  copy:
    content: "{{ ip_int_node }}"
    dest: app_internal_ip.txt

- name: save internal ip locally
  fetch:
    dest: "temp/{{ region }}/app_internal_ip{{ ip_int_node }}.txt"
    src: app_internal_ip.txt
    flat: yes

- name: save internal ip locally without ip in name
  fetch:
    dest: "temp/{{ region }}/app_internal_ip.txt"
    src: app_internal_ip.txt
    flat: yes
