- name: copy systems location sql script
  copy:
    src: system_locations.sql
    dest: system_locations.sql    

- name: copy vector_enable.sql
  copy:
    src: vector_enable.sql
    dest: vector_enable.sql

- name: copy create user sql script
  template:
    src: create_user.j2
    dest: create_user.sql    

#  fixed this to be an upsert
- name: install system locations
  shell:
    cmd: "cockroach sql --certs-dir=certs --file=system_locations.sql"

- name: create admin user
  shell:
    cmd: "cockroach sql --certs-dir=certs --file=create_user.sql"

- name: enable vector
  shell:
    cmd: "cockroach sql --certs-dir=certs --file=vector_enable.sql"
