- name: init crdb
  include_tasks: crdb_init.yml

- name: cockroachdb setup database
  include_tasks: crdb_setup.yml

- name: add enterprise license 
  include_tasks: install_enterprise_keys.yml
  when:
    - install_enterprise_keys|bool

- name: enable rangefeed
  include_tasks: crdb_enable_rangefeed.yml
