- name: Verify the disk exists
  become: yes
  command: lsblk -no NAME "{{ disk_device }}"
  register: disk_check
  failed_when: disk_check.rc != 0

- name: Check if the partition exists
  become: yes
  command: lsblk -no NAME "{{ disk_device }}1"
  register: partition_check
  failed_when: false
  changed_when: false

- name: Partition the disk if not already partitioned
  become: yes
  shell: |
    echo -e "n\np\n1\n\n\nw" | fdisk "{{ disk_device }}"
  when: "'%s1' % (disk_device | basename) not in partition_check.stdout"

- name: Reload partition table
  become: yes
  command: partprobe "{{ disk_device }}"
  when: "'%s1' % (disk_device | basename) not in partition_check.stdout"

- name: Check current filesystem type
  become: yes
  command: blkid -s TYPE -o value "{{ disk_device }}1"
  register: fs_check
  failed_when: false
  changed_when: false

- name: Format the partition if not already formatted or if filesystem differs
  become: yes
  filesystem:
    fstype: xfs
    dev: "{{ disk_device }}1"
    force: true
  when: fs_check.stdout is undefined or fs_check.stdout != "xfs"

- name: Create mount point
  become: yes
  file:
    path: "{{ crdb_file_location }}"
    state: directory

- name: Check if the partition is mounted
  become: yes
  shell: mount | grep -w "{{ disk_device }}1"
  register: mount_check
  failed_when: false
  changed_when: false

- name: Mount the disk if not already mounted
  become: yes
  mount:
    path: "{{ crdb_file_location }}"
    src: "{{ disk_device }}1"
    fstype: xfs
    opts: defaults
    state: mounted
  when: mount_check.stdout == ""

- name: Fetch partition UUID
  become: yes
  command: blkid -s UUID -o value "{{ disk_device }}1"
  register: blkid_output

- name: Ensure fstab entry exists
  become: yes
  lineinfile:
    dest: /etc/fstab
    line: "UUID={{ blkid_output.stdout }} {{ crdb_file_location }} xfs defaults 0 2"
    state: present

- name: Set ownership and permissions for admin user directory
  become: yes
  file:
    path: "{{ crdb_file_location }}/{{ admin_username }}"
    state: directory
    owner: "{{ admin_username }}"
    mode: '0755'
