- name: generate node certs
  shell:
    cmd: "cockroach cert create-node {{ inventory_hostname }} {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} localhost {{load_balancer_private_ip}} {{load_balancer_public_ip}} --certs-dir=certs --ca-key=my-safe-directory/ca.key"
    creates: certs/node.crt
- name: generate client certs
  shell:
    cmd: "cockroach cert create-client root --certs-dir=certs --ca-key=my-safe-directory/ca.key"
    creates: certs/client.root.key
