- name: Check cockroach health status
  uri:
    url: "http://localhost:8080/health"
    method: GET
    return_content: yes
    validate_certs: no
    follow_redirects: all
    headers:
        cache-control: no-cache
  register: crdb_health_result
  ignore_errors: true

- name: print the return value
  debug:
    var: crdb_health_result

- name: start crdb allowing non-tls
  shell:
    cmd: "cockroach start --locality=region={{ region }} --certs-dir=certs --advertise-addr={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} --join={{ join_string }} --max-offset=250ms --store={{ crdb_file_location }}/{{ admin_username }}/cockroach-data  --accept-sql-without-tls --background"
  when: 
    - crdb_health_result.status < 0
    - allow_non_tls|bool

- name: start crdb not allowing tls
  shell:
    cmd: "cockroach start --locality=region={{ region }} --certs-dir=certs --advertise-addr={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} --join={{ join_string }} --max-offset=250ms --store={{ crdb_file_location }}/{{ admin_username }}/cockroach-data --background"
  when: 
    - crdb_health_result.status < 0
    - not allow_non_tls|bool
