- name: Deploy cockroach.service via Jinja2 template
  become: yes
  ansible.builtin.template:
    src: cockroach.service.j2
    dest: /etc/systemd/system/cockroach.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd so it notices our new unit
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable & start cockroach.service
  become: yes
  ansible.builtin.systemd:
    name: cockroach.service
    enabled: yes
    state: started
